// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.StartDebugSessionRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.AddBookmarkRequest;
import com.probestack.forgestudio.design.model.StartDebugSessionRequest;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class SessionsServiceTest {

    private final StartDebugSessionRequestDomainRepository repository = mock(StartDebugSessionRequestDomainRepository.class);
    private final SessionsService service = new SessionsService(repository, mock(BusinessOperationLogger.class));

    private static StartDebugSessionRequest entity() {
        StartDebugSessionRequest entity = new StartDebugSessionRequest();
        return entity;
    }

    @Test
    void addBookmark_isNotImplementedUntilBusinessLogicExists() {
        assertThrows(RuntimeException.class, () -> service.addBookmark(UUID.fromString("00000000-0000-0000-0000-000000000001"), new AddBookmarkRequest()));
    }

    @Test
    void getDebugSession_returnsTheEntityWhenItExists() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        var response = service.getDebugSession(UUID.fromString("00000000-0000-0000-0000-000000000001"), true, true);
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
    }

    @Test
    void getDebugSession_failsWhenTheEntityDoesNotExist() {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        assertThrows(RuntimeException.class, () -> service.getDebugSession(UUID.fromString("00000000-0000-0000-0000-000000000001"), true, true));
    }

    @Test
    void startDebugSession_savesTheEntityAndReturnsSuccess() {
        when(repository.save(org.mockito.ArgumentMatchers.any(StartDebugSessionRequest.class))).thenAnswer(invocation -> invocation.getArgument(0));
        var response = service.startDebugSession(entity());
        assertTrue(response.getStatusCode().is2xxSuccessful());
        assertNotNull(response.getBody());
        verify(repository).save(ArgumentMatchers.any(StartDebugSessionRequest.class));
    }

}
