package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.SessionListDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.SessionList;
import com.probestack.forgestudio.design.model.SessionListContentInner;
import java.lang.reflect.Method;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import org.springframework.beans.BeanUtils;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for SessionList operations.
 *
 * <p>This service depends on a persistence-neutral domain repository port.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class ReplaysService {
    private final SessionListDomainRepository sessionListDomainRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public ReplaysService(SessionListDomainRepository sessionListDomainRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.sessionListDomainRepository = sessionListDomainRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<SessionList> searchDebugSessions(String q, String engineerId,
            String targetSystem, String incidentId, String bookmarkType, String status,
            OffsetDateTime fromDate, OffsetDateTime toDate, Integer page, Integer size) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve all entities from database
            List<SessionList> entities = sessionListDomainRepository.findAll();
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("searchDebugSessions")
                            .resource("SessionList")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("SessionListDomainRepository")
                            .collection("production_debug_recorder_replays")
                            .recordCount(entities.size())
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Step 1: Map persisted entities to the OpenAPI wrapper item DTOs
            List<SessionListContentInner> responses = entities.stream().map(this::mapToSessionListContentInner).collect(Collectors.toList());
            // Step 2: Create the OpenAPI list wrapper and populate its list property
            SessionList response = new SessionList();
            response.setContent(responses);
            // Step 3: Return the wrapper response required by the API contract
            return ResponseEntity.ok(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("searchDebugSessions")
                            .resource("SessionList")
                            .action("READ")
                            .status("FAILED")
                            .repository("SessionListDomainRepository")
                            .collection("production_debug_recorder_replays")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps SessionList entity to SessionListContentInner response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private SessionListContentInner mapToSessionListContentInner(SessionList entity) {
        // Create new response object
        SessionListContentInner response = new SessionListContentInner();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
