package com.probestack.forgestudio.design.service;

import com.probestack.forgestudio.design.domain.repository.StartDebugSessionRequestDomainRepository;
import com.probestack.forgestudio.design.exception.ApiException;
import com.probestack.forgestudio.design.logging.BusinessOperationEvent;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.AddBookmarkRequest;
import com.probestack.forgestudio.design.model.Bookmark;
import com.probestack.forgestudio.design.model.DebugSession;
import com.probestack.forgestudio.design.model.DebugSessionRecordedStepsInner;
import com.probestack.forgestudio.design.model.StartDebugSessionRequest;
import java.lang.reflect.Method;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.beans.BeanUtils;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

/**
 * Service layer for StartDebugSessionRequest operations.
 *
 * <p>This service depends on a persistence-neutral domain repository port.</p>
 *
 * @author Generated by ProbeStack CodeGen
 * <p>Note: Mapper methods use BeanUtils.copyProperties() for automatic field mapping.</p>
 */
@Service
public class SessionsService {
    private final StartDebugSessionRequestDomainRepository startDebugSessionRequestDomainRepository;

    private final BusinessOperationLogger businessOperationLogger;

    public SessionsService(
            StartDebugSessionRequestDomainRepository startDebugSessionRequestDomainRepository,
            BusinessOperationLogger businessOperationLogger) {
        this.startDebugSessionRequestDomainRepository = startDebugSessionRequestDomainRepository;
        this.businessOperationLogger = businessOperationLogger;
    }

    public ResponseEntity<Bookmark> addBookmark(UUID sessionId,
            AddBookmarkRequest addBookmarkRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // TODO: Implement custom business logic
            // Available repository methods:
            //   - save(entity) - Create or update
            //   - findById(id) - Find by ID
            //   - findAll() - Get all entities
            //   - existsById(id) - Check if exists
            //   - deleteById(id) - Delete by ID
            //   - count() - Count all entities
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("addBookmark")
                            .resource("StartDebugSessionRequest")
                            .action("UNKNOWN")
                            .status("NOT_IMPLEMENTED")
                            .repository("StartDebugSessionRequestRepository")
                            .collection("production_debug_recorder_sessions")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            throw ApiException.notImplemented("Generated operation addBookmark requires custom business logic");
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("addBookmark")
                            .resource("StartDebugSessionRequest")
                            .action("CREATE")
                            .status("FAILED")
                            .repository("StartDebugSessionRequestDomainRepository")
                            .collection("production_debug_recorder_sessions")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_write_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<DebugSession> getDebugSession(UUID sessionId, Boolean includeOutput,
            Boolean redacted) {
        long businessStartedAt = System.nanoTime();
        try {
            // Retrieve entity by ID from database
            String repositoryId = toRepositoryId(sessionId);
            Optional<StartDebugSessionRequest> entity = startDebugSessionRequestDomainRepository.findById(repositoryId);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getDebugSession")
                            .resource("StartDebugSessionRequest")
                            .action("READ")
                            .status("SUCCESS")
                            .repository("StartDebugSessionRequestDomainRepository")
                            .collection("production_debug_recorder_sessions")
                            .documentId(repositoryId)
                            .recordCount(entity.isPresent() ? 1 : 0)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            return entity.map(this::mapToDebugSession).map(ResponseEntity::ok).orElseThrow(() -> ApiException.notFound("StartDebugSessionRequest", repositoryId));
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("getDebugSession")
                            .resource("StartDebugSessionRequest")
                            .action("READ")
                            .status("FAILED")
                            .repository("StartDebugSessionRequestDomainRepository")
                            .collection("production_debug_recorder_sessions")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_read_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    public ResponseEntity<DebugSession> startDebugSession(
            StartDebugSessionRequest startDebugSessionRequest) {
        long businessStartedAt = System.nanoTime();
        try {
            // Save the entity to database
            ensureEntityId(startDebugSessionRequest);
            StartDebugSessionRequest savedStartDebugSessionRequest = startDebugSessionRequestDomainRepository.save(startDebugSessionRequest);
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("startDebugSession")
                            .resource("StartDebugSessionRequest")
                            .action("CREATE")
                            .status("SUCCESS")
                            .repository("StartDebugSessionRequestDomainRepository")
                            .collection("production_debug_recorder_sessions")
                            .documentId(getEntityId(savedStartDebugSessionRequest))
                            .recordCount(1)
                            .durationMs(businessDurationMs(businessStartedAt))
                            .build());
            // Map entity to response DTO
            DebugSession response = mapToDebugSession(savedStartDebugSessionRequest);
            return ResponseEntity.status(HttpStatus.CREATED).body(response);
        } catch (RuntimeException exception) {
            businessOperationLogger.record(BusinessOperationEvent.builder()
                            .operation("startDebugSession")
                            .resource("StartDebugSessionRequest")
                            .action("CREATE")
                            .status("FAILED")
                            .repository("StartDebugSessionRequestDomainRepository")
                            .collection("production_debug_recorder_sessions")
                            .durationMs(businessDurationMs(businessStartedAt))
                            .errorCode("database_write_failed")
                            .errorMessage(exception.getMessage())
                            .build(), exception);
            throw exception;
        }
    }

    /**
     * Converts OpenAPI path IDs to the repository ID type.
     */
    private String toRepositoryId(Object id) {
        if (id == null) {
            return null;
        }
        return id.toString();
    }

    /**
     * Assigns a Mongo document ID when the generated model does not have one yet.
     */
    private void ensureEntityId(Object entity) {
        if (entity == null) {
            return;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object currentId = getter.invoke(entity);
            if (currentId == null || currentId.toString().isBlank()) {
                setEntityId(entity, UUID.randomUUID().toString());
            }
        } catch (Exception ignored) {
            // Generated models are enhanced with getId/setId; ignore if custom code removed them.
        }
    }

    private void setEntityId(Object entity, String id) {
        if (entity == null || id == null) {
            return;
        }
        try {
            Method setter = entity.getClass().getMethod("setId", String.class);
            setter.invoke(entity, id);
        } catch (Exception ignored) {
            // Generated models are enhanced with setId; ignore if custom code removed it.
        }
    }

    private String getEntityId(Object entity) {
        if (entity == null) {
            return null;
        }
        try {
            Method getter = entity.getClass().getMethod("getId");
            Object value = getter.invoke(entity);
            return value != null ? value.toString() : null;
        } catch (Exception ignored) {
            return null;
        }
    }

    private void copyGeneratedId(Object entity, Object response) {
        String id = getEntityId(entity);
        if (id == null || response == null) {
            return;
        }
        for (Method method : response.getClass().getMethods()) {
            if (method.getName().startsWith("set") && method.getName().endsWith("Id") && method.getParameterCount() == 1 && method.getParameterTypes()[0].equals(String.class)) {
                try {
                    method.invoke(response, id);
                    return;
                } catch (Exception ignored) {
                    // Try the next compatible ID setter.
                }
            }
        }
    }

    /**
     * Creates an empty response wrapper for list/search endpoints.
     */
    private <T> T emptyResponse(Class<T> responseType) {
        try {
            T response = responseType.getDeclaredConstructor().newInstance();
            for (Method method : responseType.getMethods()) {
                if (method.getName().startsWith("set") && method.getParameterCount() == 1 && List.class.isAssignableFrom(method.getParameterTypes()[0])) {
                    method.invoke(response, Collections.emptyList());
                }
            }
            return response;
        } catch (Exception ignored) {
            return null;
        }
    }

    /**
     * Calculates elapsed milliseconds for generated business operation logs.
     */
    private Long businessDurationMs(long startedAt) {
        return (System.nanoTime() - startedAt) / 1_000_000L;
    }

    /**
     * Maps StartDebugSessionRequest entity to Bookmark response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private Bookmark mapToBookmark(StartDebugSessionRequest entity) {
        // Create new response object
        Bookmark response = new Bookmark();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps StartDebugSessionRequest entity to DebugSessionRecordedStepsInner response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private DebugSessionRecordedStepsInner mapToDebugSessionRecordedStepsInner(
            StartDebugSessionRequest entity) {
        // Create new response object
        DebugSessionRecordedStepsInner response = new DebugSessionRecordedStepsInner();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }

    /**
     * Maps StartDebugSessionRequest entity to DebugSession response DTO.
     *
     * <p>Uses Spring BeanUtils.copyProperties() to automatically copy matching fields.</p>
     *
     * @param entity the entity to map
     * @return mapped response DTO
     */
    private DebugSession mapToDebugSession(StartDebugSessionRequest entity) {
        // Create new response object
        DebugSession response = new DebugSession();
        // Copy matching properties from entity to response
        BeanUtils.copyProperties(entity, response);
        copyGeneratedId(entity, response);
        // 
        // TODO: Add custom field mappings here if needed
        // Example:
        //   response.setCustomField(entity.getSourceField());
        //   response.setMessage("Success");
        // 
        return response;
    }
}
