/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.probestack.forgestudio.design.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.probestack.forgestudio.design.model.ErrorResponse;
import java.time.OffsetDateTime;
import com.probestack.forgestudio.design.model.SessionList;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-10-06T03:07:24.471763475Z[GMT]")@Validated
@Tag(name = "Replays", description = "Replay past debug sessions for learning.")
public interface ReplaysApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /sessions : Search and list past debug sessions
     * Full-text search across all past debug sessions — commands, outputs,  bookmarks, and metadata. Used by engineers to find \&quot;how did someone  fix this before?\&quot; and by managers to measure debugging patterns  across the team. 
     *
     * @param q Full-text query across commands, outputs, and titles. (optional)
     * @param engineerId Filter by engineer. (optional)
     * @param targetSystem Filter by system. (optional)
     * @param incidentId Filter by incident. (optional)
     * @param bookmarkType Filter by bookmark type. (optional)
     * @param status Filter by session status. (optional)
     * @param fromDate Only include sessions started after this time. (optional)
     * @param toDate Only include sessions started before this time. (optional)
     * @param page Page number (zero-based). (optional, default to 0)
     * @param size Number of items per page. (optional, default to 20)
     * @return List of matching debug sessions. (status code 200)
     *         or Invalid request payload or missing required fields. (status code 400)
     *         or Internal server error. (status code 500)
     */
    @Operation(
        operationId = "searchDebugSessions",
        summary = "Search and list past debug sessions",
        description = "Full-text search across all past debug sessions — commands, outputs,  bookmarks, and metadata. Used by engineers to find \"how did someone  fix this before?\" and by managers to measure debugging patterns  across the team. ",
        tags = { "Replays" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of matching debug sessions.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SessionList.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid request payload or missing required fields.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/sessions",
        produces = { "application/json" }
    )
    
    default ResponseEntity<SessionList> searchDebugSessions(
        @Parameter(name = "q", description = "Full-text query across commands, outputs, and titles.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "q", required = false) String q,
        @Parameter(name = "engineerId", description = "Filter by engineer.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "engineerId", required = false) String engineerId,
        @Parameter(name = "targetSystem", description = "Filter by system.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "targetSystem", required = false) String targetSystem,
        @Parameter(name = "incidentId", description = "Filter by incident.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "incidentId", required = false) String incidentId,
        @Parameter(name = "bookmarkType", description = "Filter by bookmark type.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "bookmarkType", required = false) String bookmarkType,
        @Parameter(name = "status", description = "Filter by session status.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "status", required = false) String status,
        @Parameter(name = "fromDate", description = "Only include sessions started after this time.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "fromDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime fromDate,
        @Parameter(name = "toDate", description = "Only include sessions started before this time.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "toDate", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) OffsetDateTime toDate,
        @Parameter(name = "page", description = "Page number (zero-based).", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Max(100) @Parameter(name = "size", description = "Number of items per page.", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size
    ) {
                        getRequest().ifPresent(request -> {
                    for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                        if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                            String exampleString = "{ \"size\" : 20, \"totalPages\" : 18, \"page\" : 0, \"content\" : [ { \"durationSeconds\" : 1245, \"totalSteps\" : 42, \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"matchHighlights\" : [ \"...HikariCP pool maxed at 20, wait queue at 500ms+...\", \"...connection pool exhaustion confirmed via metrics...\" ], \"sessionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"Payment timeout investigation - 2026-10-06\", \"targetSystem\" : \"payment-processor\", \"environment\" : \"PRODUCTION\", \"rootCauseSummary\" : \"Thread pool exhaustion caused by slow downstream API.\", \"engineerId\" : \"amit.kumar@forgesphere.example.com\", \"bookmarksCount\" : 3, \"incidentId\" : \"INC-2050\", \"status\" : \"COMPLETED\" }, { \"durationSeconds\" : 1245, \"totalSteps\" : 42, \"startedAt\" : \"2000-01-23T04:56:07.000+00:00\", \"matchHighlights\" : [ \"...HikariCP pool maxed at 20, wait queue at 500ms+...\", \"...connection pool exhaustion confirmed via metrics...\" ], \"sessionId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"Payment timeout investigation - 2026-10-06\", \"targetSystem\" : \"payment-processor\", \"environment\" : \"PRODUCTION\", \"rootCauseSummary\" : \"Thread pool exhaustion caused by slow downstream API.\", \"engineerId\" : \"amit.kumar@forgesphere.example.com\", \"bookmarksCount\" : 3, \"incidentId\" : \"INC-2050\", \"status\" : \"COMPLETED\" } ], \"totalElements\" : 342 }";
                            ApiUtil.setExampleResponse(request, "application/json", exampleString);
                            break;
                        }
                    }
                });
                return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
                                                            }

}
