// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.advice.GlobalExceptionHandler;
import com.probestack.forgestudio.design.config.validation.ValidationProperties;
import com.probestack.forgestudio.design.domain.repository.SessionListDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.SessionList;
import com.probestack.forgestudio.design.service.ReplaysService;
import com.probestack.forgestudio.design.validation.GeneratedRequestValidator;
import jakarta.validation.Validation;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class ReplaysApiControllerIntegrationTest {

    private final SessionListDomainRepository repository = mock(SessionListDomainRepository.class);
    private MockMvc mockMvc;

    private static SessionList entity() {
        SessionList entity = new SessionList();
        return entity;
    }

    @BeforeEach
    void setUp() {
        ReplaysService service = new ReplaysService(repository, mock(BusinessOperationLogger.class));
        ValidationProperties properties = new ValidationProperties();
        properties.setEnabled(true);
        GeneratedRequestValidator validator = new GeneratedRequestValidator(properties,
                Validation.buildDefaultValidatorFactory().getValidator());
        ReplaysApiController controller = new ReplaysApiController(service, validator);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler())
                .addPlaceholderValue("openapi.productionDebugRecorder.base-path", "/v1")
                .build();
    }

    @Test
    void searchDebugSessions_returnsEveryEntity() throws Exception {
        when(repository.findAll()).thenReturn(List.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/sessions"))
                .andExpect(status().is2xxSuccessful());
    }

}
