// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.api;

import com.probestack.forgestudio.design.advice.GlobalExceptionHandler;
import com.probestack.forgestudio.design.config.validation.ValidationProperties;
import com.probestack.forgestudio.design.domain.repository.StartDebugSessionRequestDomainRepository;
import com.probestack.forgestudio.design.logging.BusinessOperationLogger;
import com.probestack.forgestudio.design.model.StartDebugSessionRequest;
import com.probestack.forgestudio.design.service.SessionsService;
import com.probestack.forgestudio.design.validation.GeneratedRequestValidator;
import jakarta.validation.Validation;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class SessionsApiControllerIntegrationTest {

    private final StartDebugSessionRequestDomainRepository repository = mock(StartDebugSessionRequestDomainRepository.class);
    private MockMvc mockMvc;

    private static StartDebugSessionRequest entity() {
        StartDebugSessionRequest entity = new StartDebugSessionRequest();
        return entity;
    }

    @BeforeEach
    void setUp() {
        SessionsService service = new SessionsService(repository, mock(BusinessOperationLogger.class));
        ValidationProperties properties = new ValidationProperties();
        properties.setEnabled(true);
        GeneratedRequestValidator validator = new GeneratedRequestValidator(properties,
                Validation.buildDefaultValidatorFactory().getValidator());
        SessionsApiController controller = new SessionsApiController(service, validator);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler())
                .addPlaceholderValue("openapi.productionDebugRecorder.base-path", "/v1")
                .build();
    }

    @Test
    void startDebugSession_createsTheEntity() throws Exception {
        when(repository.save(org.mockito.ArgumentMatchers.any(StartDebugSessionRequest.class))).thenAnswer(invocation -> invocation.getArgument(0));
        mockMvc.perform(request(HttpMethod.POST, "/v1/sessions")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"title\":\"Payment timeout investigation - 2026-10-06\",\"engineerId\":\"amit.kumar@forgesphere.example.com\",\"targetSystem\":\"payment-processor\",\"environment\":\"PRODUCTION\",\"purpose\":\"Investigating 5xx spike on /charge endpoint since 14:00 UTC.\",\"incidentId\":\"INC-2050\",\"maxDurationMinutes\":120,\"captureMode\":\"SHELL_AND_HTTP\",\"redactPatterns\":[\"password=.*\",\"token=.*\",\"\\\\b\\\\d{16}\\\\b\"],\"shareWith\":[\"payments-team\",\"sre-team@forgesphere.example.com\"]}"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void startDebugSession_rejectsMalformedJson() throws Exception {
        mockMvc.perform(request(HttpMethod.POST, "/v1/sessions")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{"))
                .andExpect(status().isBadRequest());
    }

    @Test
    void getDebugSession_returnsTheEntity() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.of(entity()));
        mockMvc.perform(request(HttpMethod.GET, "/v1/sessions/{sessionId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().is2xxSuccessful());
    }

    @Test
    void getDebugSession_isNotFoundWhenTheEntityDoesNotExist() throws Exception {
        when(repository.findById(ArgumentMatchers.anyString())).thenReturn(Optional.empty());
        mockMvc.perform(request(HttpMethod.GET, "/v1/sessions/{sessionId}", "00000000-0000-0000-0000-000000000001"))
                .andExpect(status().isNotFound());
    }

}
