// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.persistence.mongodb.adapter;

import com.probestack.forgestudio.design.model.SessionList;
import com.probestack.forgestudio.design.persistence.mongodb.document.SessionListDocument;
import com.probestack.forgestudio.design.persistence.mongodb.repository.SessionListMongoRepository;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class SessionListMongoPersistenceAdapterTest {

    private final SessionListMongoRepository repository = mock(SessionListMongoRepository.class);
    private final SessionListMongoPersistenceAdapter adapter = new SessionListMongoPersistenceAdapter(repository);

    private static SessionList domain() {
        SessionList domain = new SessionList();
        return domain;
    }

    private static SessionListDocument stored() {
        SessionListDocument stored = new SessionListDocument();
        return stored;
    }

    @Test
    void save_mapsToThePersistenceModelAndBack() {
        when(repository.save(ArgumentMatchers.any(SessionListDocument.class))).thenAnswer(invocation -> invocation.getArgument(0));
        SessionList saved = adapter.save(domain());
        ArgumentCaptor<SessionListDocument> captor = ArgumentCaptor.forClass(SessionListDocument.class);
        verify(repository).save(captor.capture());
        assertNotNull(saved);
    }

    @Test
    void findById_mapsAStoredEntityToTheDomainModel() {
        when(repository.findById("id-1")).thenReturn(Optional.of(stored()));
        Optional<SessionList> found = adapter.findById("id-1");
        assertTrue(found.isPresent());
    }

    @Test
    void findById_isEmptyWhenNothingIsStored() {
        when(repository.findById("id-1")).thenReturn(Optional.empty());
        assertTrue(adapter.findById("id-1").isEmpty());
    }

    @Test
    void findAll_mapsEveryStoredEntity() {
        when(repository.findAll()).thenReturn(List.of(stored()));
        List<SessionList> all = adapter.findAll();
        assertEquals(1, all.size());
    }

    @Test
    void existsById_delegatesToTheRepository() {
        when(repository.existsById("id-1")).thenReturn(true);
        assertTrue(adapter.existsById("id-1"));
    }

    @Test
    void deleteById_delegatesToTheRepository() {
        adapter.deleteById("id-1");
        verify(repository).deleteById("id-1");
    }

    @Test
    void count_delegatesToTheRepository() {
        when(repository.count()).thenReturn(3L);
        assertEquals(3L, adapter.count());
    }

}
