// Generated by ProbeStack CodeGen. Safe to edit.
package com.probestack.forgestudio.design.persistence.mongodb.adapter;

import com.probestack.forgestudio.design.model.StartDebugSessionRequest;
import com.probestack.forgestudio.design.persistence.mongodb.document.StartDebugSessionRequestDocument;
import com.probestack.forgestudio.design.persistence.mongodb.repository.StartDebugSessionRequestMongoRepository;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class StartDebugSessionRequestMongoPersistenceAdapterTest {

    private final StartDebugSessionRequestMongoRepository repository = mock(StartDebugSessionRequestMongoRepository.class);
    private final StartDebugSessionRequestMongoPersistenceAdapter adapter = new StartDebugSessionRequestMongoPersistenceAdapter(repository);

    private static StartDebugSessionRequest domain() {
        StartDebugSessionRequest domain = new StartDebugSessionRequest();
        return domain;
    }

    private static StartDebugSessionRequestDocument stored() {
        StartDebugSessionRequestDocument stored = new StartDebugSessionRequestDocument();
        return stored;
    }

    @Test
    void save_mapsToThePersistenceModelAndBack() {
        when(repository.save(ArgumentMatchers.any(StartDebugSessionRequestDocument.class))).thenAnswer(invocation -> invocation.getArgument(0));
        StartDebugSessionRequest saved = adapter.save(domain());
        ArgumentCaptor<StartDebugSessionRequestDocument> captor = ArgumentCaptor.forClass(StartDebugSessionRequestDocument.class);
        verify(repository).save(captor.capture());
        assertNotNull(saved);
    }

    @Test
    void findById_mapsAStoredEntityToTheDomainModel() {
        when(repository.findById("id-1")).thenReturn(Optional.of(stored()));
        Optional<StartDebugSessionRequest> found = adapter.findById("id-1");
        assertTrue(found.isPresent());
    }

    @Test
    void findById_isEmptyWhenNothingIsStored() {
        when(repository.findById("id-1")).thenReturn(Optional.empty());
        assertTrue(adapter.findById("id-1").isEmpty());
    }

    @Test
    void findAll_mapsEveryStoredEntity() {
        when(repository.findAll()).thenReturn(List.of(stored()));
        List<StartDebugSessionRequest> all = adapter.findAll();
        assertEquals(1, all.size());
    }

    @Test
    void existsById_delegatesToTheRepository() {
        when(repository.existsById("id-1")).thenReturn(true);
        assertTrue(adapter.existsById("id-1"));
    }

    @Test
    void deleteById_delegatesToTheRepository() {
        adapter.deleteById("id-1");
        verify(repository).deleteById("id-1");
    }

    @Test
    void count_delegatesToTheRepository() {
        when(repository.count()).thenReturn(3L);
        assertEquals(3L, adapter.count());
    }

}
